name: Sphinx shtest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install Python dependencies.
        run: pip install -r requirements.txt
      - name: Lint the code.
        run: cook exec lint
      - name: Run the tests.
        run: cook exec tests
      - name: Build the documentation.
        run: cook exec 'docs*'
      - name: Build a package.
        run: cook exec 'package*'
      - name: Publish to PyPI.
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.python-version == '3.10'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
